fixed readme
ZupIT/docs-charles pull request #97
Opened 2021-11-09 17:24 UTC by jessica-tw

Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>

- Fixed docs readme.

2021-11-09 17:43 UTC, barbararochazup requested changes

2021-11-09 17:43 UTC, barbararochazup commented on README.md
> +his repository uses [**hugo server**](https://gohugo.io/commands/hugo_server/) and contains **[CharlesCD](https://charlescd.io/)** official documentation.
Missing **T** letter on This

2021-11-09 17:43 UTC, barbararochazup commented on README.md
> +Check out Ritchie's [**contributing guide**](https://github.com/ZupIT/charlescd/blob/main/CONTRIBUTING.md).
Change Ritchie's to CharlesCD 's

Another question, we have a CONTRIBUTIND.md on docs repo https://github.com/ZupIT/docs-charles/blob/main/CONTRIBUTING.md.  Why reference to charlescd repo?

2021-11-09 17:43 UTC, barbararochazup commented on README.md
>  **Step 1.** Access [**GitHub Issues**](https://github.com/ZupIT/docs-horusec/issues) and open an issue;
Change link to https://github.com/ZupIT/docs-charles/issues

2021-11-09 17:51 UTC, jessica-tw commented on README.md
> +Check out Ritchie's [**contributing guide**](https://github.com/ZupIT/charlescd/blob/main/CONTRIBUTING.md).
Adding this one ;)

2021-11-16 17:41 UTC, barbararochazup submitted a review, later dismissed

2021-11-16 21:26 UTC, mdcpmoreira approved these changes

2021-11-16 21:26 UTC, mdcpmoreira commented on CONTRIBUTING.md
> +If you have any questions or ideas, let's chat in our [**Zup Open Source Forum**](https://forum.zup.com.br).
```suggestion
Do you have any question about CharlesCD? Let's chat in our [**Zup Open Source Forum**](https://forum.zup.com.br).
```

2021-11-16 21:26 UTC, mdcpmoreira commented on README.md
> +If you have any questions or ideas, let's chat in our [**Zup Open Source Forum**](https://forum.zup.com.br) or [**GitHub Issues**](https://github.com/ZupIT/docs-charles/issues).
```suggestion
Do you have any questions or ideas? Let's chat in our [**Zup Open Source Forum**](https://forum.zup.com.br) or [**GitHub Issues**](https://github.com/ZupIT/docs-charles/issues).
```

2021-11-18 18:47 UTC, barbararochazup approved these changes

2021-12-10 14:12 UTC, mdcpmoreira approved these changes

2021-12-10 20:04 UTC, otaviojava approved these changes

2022-01-10 17:18 UTC, merged